language: r
os: linux
sudo: required
cache: packages

r:
  - 3.4
  - devel

after_success:
  - Rscript -e 'library(rave)'
after_failure:
  - ./travis-tool.sh dump_logs
warnings_are_errors: true


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libfftw3-dev
      - libv8-3.14-dev
      - libxml2-dev

notifications:
  email: false


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone "https://github.com/Linuxbrew/brew.git ~/.linuxbrew"; export HOMEBREW_FORCE_VENDOR_RUBY=1; PATH="$HOME/.linuxbrew/bin:$PATH"; brew install hdf5

