debug: FALSE
raw_data_dir: ../Researches/rave/adhoc/Dipterix/Data/ECoG/neuralData/originalData/
data_dir: ../rafe/hdf5_data/
big_object_size: 500000
server_time_zone: America/Chicago
module_export: ./export
content_regex: e([0-9]+)[^0-9]*
content_format: mat
module_lookup_file: ./modules.csv
delay_input: 200
max_worker: 20
export_path: ./export
temp_dir: temp
suma_monitor_dir: temp/monitor
suma_export_dir: suma
suma_to_niml: ~/abin/ConvertDset -o_niml -input %s -i_1D -node_index_1D %s -prefix %s
suma_send_niml: ~/abin/DriveSuma -com surf_cont -load_dset %s
suma_nodes_per_electrodes: 42
suma_parallel_cores: 2
suma_gifti_name_regex: electrode_[a-zA-Z0-9]+.gii
suma_path: ~/abin
suma_spec_file: test.spec
unbuffer_path: /usr/local/bin
matlab_path: /Applications/MATLAB_R2016b.app/bin
batch_bytes: 5000000000
image_width: 1280
image_height: 768
